### ISSUE TITLE
استاپ شدن سرویس

### ISSUE THREAD

**Issue by ohum123** [mmtaee/ocserv-users-management#42]
سرویس user_stats.service هر از گاهی خود به خود استاپ میشه و دیگه ترافیک یوزرا قابل کنترل نیست
ubuntu 20.04 
نصب هم از طریق اسکریپت و ونصب کامل همراه با ocserv و پنل
اروری که میگیرم 
Traceback (most recent call last):
  File "/var/www/site/back-end/user_stats.py", line 46, in check_stats
    ocserv_user = OcservUser.objects.get(username=username)
  File "/var/www/site/back-end/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/site/back-end/venv/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
app.models.DoesNotExist: OcservUser matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/site/back-end/user_stats.py", line 80, in <module>
    check_stats(OcservUser, MonthlyTrafficStat, OcservUserHandler, Logger)
  File "/var/www/site/back-end/user_stats.py", line 69, in check_stats
    except OcservUser.DoesNotExist():
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by mmtaee** [comment]
#
